services:
  infinity:
    image: infi
    build:
      context: .
      network: host
    volumes:
    - /data/huggingface:/root/huggingface
    - /home/lianghao/workspace/Infinity:/workspace/Infinity
    command: bash
    stdin_open: true
    tty: true
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

