# 这个文件用于覆盖默认配置
# 只需要包含要修改的参数

# 修改模型参数
init_args:
  root_folder: '/home/Infinity'

gen_kwargs:
  partion_on_full_scale: true # if true, analyze on 64x64 summation code, else analyze on per-scale interpolated code
  pruning: 2 # 0: prune nothing 1: prune outputs 2: prune inouts
  causal: 1
  rope2d_opt_level: 1
  using_flash: 1
  si_para: 8
  ratio_list: [[50,30,10,10],[30,10,0,0]]